version: "3.3"

services:
  peertube-seeder-dev:
    container_name: seedtuber-dev
    image: seedtuber-dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      peertube_url: "https://jupiter.tube/"
      ping_interval: 5
