version: "3.3"

services:
  peertube-seeder:
    image: ghcr.io/cgbassplayer/seedtuber:latest
    environment:
      peertube_url: "https://jupiter.tube/"
      ping_interval: 300
      browser_limit: 5
    restart: unless-stopped
